import { Link, NavLink, Route, Routes, useParams } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight, BadgeCheck, Car, Check, CircleDollarSign, Compass, MapPin, Phone, ShieldCheck, Zap } from 'lucide-react'

const WSP = '56945055463'
const RED = '#D71F2E'

const models = [
  { slug:'x50', name:'X50', type:'SUV urbano', mood:'city', accent:'#d9d9d9', headline:'Compacto, moderno y listo para la ciudad.', summary:'Un SUV práctico para moverse por Santiago con diseño juvenil, buena conectividad y una propuesta de valor muy atractiva.', ideal:'Primer SUV, uso diario, ciudad y escapadas de fin de semana.', warranty:'5 años / 150.000 km', specs:[['Motor','1.5L 111 hp o 1.5T 154 hp'],['Torque','143 Nm o 230 Nm'],['Transmisión','5MT o 6DCT'],['Dimensiones','4.397 x 1.841 x 1.654 mm'],['Pasajeros','5'],['Maletero','398 / 1.262 L']], highlights:['Apple CarPlay y Android Auto inalámbrico','Doble pantalla 10,25” según versión','Tapiz eco-cuero según versión','Luces LED según versión'] },
  { slug:'new-x70', name:'New X70', type:'SUV familiar 7 pasajeros', mood:'family', accent:'#7f8793', headline:'Espacio familiar para viajar con todos.', summary:'Un SUV de 7 pasajeros pensado para familias que necesitan más espacio, comodidad y versatilidad.', ideal:'Familias, viajes largos, clientes que necesitan 7 asientos.', warranty:'5 años / 150.000 km', specs:[['Motor','1.5 Turbo 145 hp'],['Torque','210 Nm'],['Transmisión','6MT o 6DCT'],['Dimensiones','4.743 x 1.900 x 1.720 mm'],['Pasajeros','7'],['Maletero','89 / 1.680 L']], highlights:['Pantalla 10,25”','Panel de instrumentos 12,3”','Tapiz eco-cuero según versión','Smart Key según versión'] },
  { slug:'x70-plus', name:'X70 Plus', type:'SUV familiar premium', mood:'premium', accent:'#59616c', headline:'Más presencia, más espacio, más categoría.', summary:'Una alternativa familiar con diseño elegante, buena habitabilidad y equipamiento pensado para subir de nivel.', ideal:'Familias que buscan presencia premium y buen equipamiento.', warranty:'5 años / 150.000 km', specs:[['Motor','1.5T 145 hp o 1.6T GDI 188 hp'],['Torque','210 / 275 Nm'],['Transmisión','DCT 6/7 vel.'],['Dimensiones','4.724 x 1.900 x 1.720 mm'],['Pasajeros','7'],['Maletero','94 / 1.688 L']], highlights:['Neumáticos 255/45 R20 según versión','Sunroof panorámico según versión','Cámara 360 HD según versión','Portalón eléctrico según versión'] },
  { slug:'dashing', name:'Dashing', type:'SUV deportivo futurista', mood:'night', accent:'#d71f2e', headline:'Diseño protagonista para quienes buscan destacar.', summary:'El SUV más emocional de la gama: líneas futuristas, cabina tecnológica y una presencia que llama la atención.', ideal:'Profesionales jóvenes, diseño deportivo, ciudad y tecnología.', warranty:'5 años / 150.000 km', specs:[['Motor','1.5T 145 hp o 1.6T GDI 188 hp'],['Torque','210 / 275 Nm'],['Transmisión','6MT, 6DCT o 7DCT'],['Dimensiones','4.590 x 1.900 x 1.685 mm'],['Pasajeros','5'],['Maletero','486 / 977 L']], highlights:['Pantalla 12,8” o 15,6” según versión','Audio Sony en versiones altas','Cámara 360 según versión','ADAS y chasis transparente según versión'] },
  { slug:'x90-plus', name:'X90 Plus', type:'SUV ejecutivo 7 pasajeros', mood:'executive', accent:'#a3a5aa', headline:'SUV ejecutivo con espacio superior.', summary:'Diseñado para quienes buscan presencia, comodidad y tecnología en un SUV de 7 pasajeros.', ideal:'Familias ejecutivas, viajes, clientes que buscan categoría superior.', warranty:'Información según versión', specs:[['Motor','2.0TGDI 241 hp'],['Torque','390 Nm'],['Transmisión','7DCT'],['Dimensiones','4.858 x 1.925 x 1.780 mm'],['Pasajeros','7'],['Maletero','104 / 1.052 L']], highlights:['Doble pantalla 12,3”','Display de climatización 9,7”','Audio Sony','ACC, AEB, BSD, LKA y TJA según versión'] },
  { slug:'t1-gasolina', name:'T1 Gasolina', type:'SUV aventura', mood:'adventure', accent:'#81917b', headline:'Carácter outdoor para explorar más.', summary:'Un SUV robusto y diferente, pensado para quienes quieren aventura sin perder comodidad diaria.', ideal:'Aventura, estilo outdoor, viajes y caminos mixtos.', warranty:'7 años / 200.000 km', specs:[['Motor','1.5T 167 hp o 2.0T 241 hp'],['Torque','290 / 390 Nm'],['Transmisión','7DCT 4x2 o 8AT XWD'],['Dimensiones','4.705 x 1.967 x 1.843 mm'],['Despeje','190 mm'],['Maletero','574 / 1.455 L']], highlights:['Modos off-road según versión','70 L de estanque','Diseño robusto tipo aventura','XWD según versión'] },
  { slug:'t1-phev', name:'T1 PHEV', type:'SUV híbrido enchufable', mood:'eco', accent:'#4db48b', headline:'Aventura híbrida con más de 1.000 km de autonomía combinada.', summary:'Combina estética outdoor con tecnología PHEV para clientes que buscan eficiencia, potencia y versatilidad.', ideal:'Tecnología híbrida, viajes largos, eficiencia y aventura.', warranty:'7 años / 200.000 km', specs:[['Potencia combinada','341 hp'],['Torque combinado','525 Nm'],['Batería','26,7 kWh LiFePO4'],['Autonomía eléctrica','117 km'],['Carga rápida','30%-80% en 0,5 h'],['Autonomía comb.','+1.000 km']], highlights:['Motor 1.5T PHEV','Carga lenta aprox. 4 h','5 pasajeros','Maletero 574 L'] },
  { slug:'t2-gasolina', name:'T2 Gasolina', type:'Off-road premium', mood:'offroad', accent:'#606b57', headline:'Presencia off-road con espíritu premium.', summary:'Un SUV imponente para clientes que buscan aventura, tecnología y una imagen poderosa.', ideal:'Off-road, viajes, montaña, clientes que quieren diferenciarse.', warranty:'7 años / 200.000 km', specs:[['Motor','2.0T GDI 241 hp'],['Torque','390 Nm'],['Transmisión','7DCT AWD'],['Dimensiones','4.785 x 2.006 x 1.880 mm'],['Despeje','220 mm'],['Maletero','580 / 1.494 L']], highlights:['Ángulo ataque 28° y salida 30°','Modos Sport, Eco, Normal, Nieve, Roca, Sedimento, Intelligent X','70 L de estanque','AWD según versión'] },
  { slug:'t2-phev', name:'T2 PHEV', type:'Híbrido enchufable premium', mood:'phev', accent:'#4e8f77', headline:'Potencia híbrida enchufable para ir más allá.', summary:'El T2 PHEV combina una estética aventurera con eficiencia eléctrica y más de 1.000 km de autonomía combinada.', ideal:'Aventura premium, eficiencia, tecnología y viajes largos.', warranty:'Información según versión', specs:[['Motor combustión','1.5 Turbo 154 hp'],['Potencia combinada','375 hp'],['Torque combinado','610 Nm'],['Batería','26,7 kWh LiFePO4'],['Autonomía eléctrica','139 km'],['Carga rápida','30 min 30%-80%']], highlights:['2 motores eléctricos','DHT 3 4x2','Despeje 205 mm','Maletero 580 / 1.494 L'] }
]

const benefits = [
  ['Respaldo', 'Atención directa de Guillermo Morales en Providencia.', BadgeCheck],
  ['Financiamiento', 'Evaluación, crédito y alternativas según perfil.', CircleDollarSign],
  ['Toma de usado', 'Renueva tu vehículo y avanza a un Jetour 0 km.', Car],
  ['Test Drive', 'Coordina una experiencia de manejo con Cristián.', Compass],
  ['Tecnología', 'Conectividad, pantallas y asistencias según versión.', Zap],
  ['Seguridad', 'Equipamiento activo y pasivo para viajar con confianza.', ShieldCheck]
]

function wsp(message='Hola Cristián, quiero cotizar un Jetour.') { return `https://wa.me/${WSP}?text=${encodeURIComponent(message)}` }
function Header(){ return <header className="nav"><Link to="/" className="brand"><span>JETOUR</span><small>Center Providencia</small></Link><nav><NavLink to="/modelos">Modelos</NavLink><NavLink to="/financiamiento">Financiamiento</NavLink><NavLink to="/test-drive">Test Drive</NavLink><NavLink to="/contacto">Contacto</NavLink></nav><a className="nav-cta" href={wsp()} target="_blank">WhatsApp</a></header> }
function Visual({model={mood:'hero',accent:RED}, large=false}){ return <div className={`visual ${model.mood||'hero'} ${large?'large':''}`} style={{'--accent':model.accent||RED}}><div className="sun"/><div className="mountain m1"/><div className="mountain m2"/><div className="road"/><div className="suv"><div className="roof"/><div className="body"/><div className="light l1"/><div className="light l2"/><div className="wheel w1"/><div className="wheel w2"/></div><span>Imagen referencial Jetour / reemplazable por fotografía oficial</span></div> }
function ModelCard({m}){ return <Link to={`/modelos/${m.slug}`} className="model-card"><Visual model={m}/><div><p>{m.type}</p><h3>{m.name}</h3><span>Explorar modelo <ArrowRight size={16}/></span></div></Link> }
function CTA({model}){ const msg=model?`Hola Cristián, quiero cotizar el Jetour ${model.name}.`:'Hola Cristián, quiero cotizar un Jetour.'; return <section className="cta-panel"><div><p className="eyebrow">Atención directa</p><h2>Agenda, cotiza o evalúa financiamiento con un asesor Jetour.</h2><p>Cristián Jiménez · Ejecutivo de Ventas Jetour · Guillermo Morales Bilbao, Providencia.</p></div><div className="cta-actions"><a className="btn primary" href={wsp(msg)} target="_blank">Cotizar por WhatsApp</a><Link className="btn ghost" to="/test-drive">Agendar Test Drive</Link></div></section> }
function Home(){ return <main><section className="hero"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.8}} className="hero-copy"><p className="eyebrow">Powered by Guillermo Morales</p><h1>Jetour Center Providencia</h1><p className="lead">SUV con diseño, tecnología y aventura para quienes buscan más. Cotiza, compara y agenda tu test drive con atención directa en Bilbao, Providencia.</p><div className="hero-actions"><a className="btn primary" href={wsp()} target="_blank">Cotizar ahora</a><Link className="btn secondary" to="/modelos">Ver modelos</Link></div></motion.div><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:1,delay:.15}}><Visual large/></motion.div></section><section className="section"><p className="eyebrow">Gama Jetour</p><div className="section-head"><h2>Elige el SUV que conecta con tu estilo de vida.</h2><Link to="/modelos">Ver todos</Link></div><div className="grid models">{models.map(m=><ModelCard key={m.slug} m={m}/>)}</div></section><section className="section dark"><p className="eyebrow">Por qué Jetour</p><div className="feature-grid">{benefits.map(([t,b,Icon])=><article className="feature" key={t}><Icon/><h3>{t}</h3><p>{b}</p></article>)}</div></section><section className="split"><div><p className="eyebrow">Aventura premium</p><h2>T1 y T2: presencia, carácter y tecnología para salir de la rutina.</h2><p>Modelos con identidad outdoor para clientes que buscan diferenciarse, viajar y vivir una experiencia SUV más completa.</p></div><Visual model={models.find(m=>m.slug==='t2-phev')} /></section><CTA/></main> }
function Models(){ return <main className="page"><section className="page-hero compact"><p className="eyebrow">Modelos</p><h1>Una gama para cada tipo de cliente.</h1><p>Compara diseño, espacio, tecnología, autonomía y enfoque comercial.</p></section><section className="section"><div className="grid models">{models.map(m=><ModelCard key={m.slug} m={m}/>)}</div></section></main> }
function ModelPage(){ const {slug}=useParams(); const model=models.find(m=>m.slug===slug)||models[0]; return <main className="page"><section className="model-hero"><div><p className="eyebrow">{model.type}</p><h1>Jetour {model.name}</h1><p className="lead">{model.headline}</p><p>{model.summary}</p><div className="hero-actions"><a className="btn primary" href={wsp(`Hola Cristián, quiero cotizar el Jetour ${model.name}.`)} target="_blank">Cotizar {model.name}</a><Link className="btn secondary" to="/test-drive">Agendar Test Drive</Link></div></div><Visual model={model} large/></section><section className="section spec-strip">{model.specs.slice(0,4).map(([l,v])=><div className="spec" key={l}><small>{l}</small><strong>{v}</strong></div>)}</section><section className="split"><div><p className="eyebrow">Descripción comercial</p><h2>{model.headline}</h2><p>{model.summary}</p><p><strong>Ideal para:</strong> {model.ideal}</p><p><strong>Garantía:</strong> {model.warranty}</p></div><div className="highlight-list">{model.highlights.map(h=><div key={h}><Check size={18}/><span>{h}</span></div>)}</div></section><section className="section"><p className="eyebrow">Ficha técnica</p><h2>Datos principales</h2><div className="tech-table">{model.specs.map(([l,v])=><div key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><p className="note">Información referencial según versión y disponibilidad. Consulte con su asesor antes de la compra.</p></section><section className="section"><p className="eyebrow">Galería contextual</p><div className="gallery"><Visual model={model}/><Visual model={{...model,mood:'interior'}}/><Visual model={{...model,mood:'detail'}}/><Visual model={{...model,mood:'roadtrip'}}/></div></section><CTA model={model}/></main> }
function Lead({title,message}){ return <section className="lead-form"><div><p className="eyebrow">Formulario rápido</p><h2>{title}</h2><p>Completa tus datos o escríbeme directo por WhatsApp para una respuesta más rápida.</p></div><form onSubmit={(e)=>{e.preventDefault(); window.open(wsp(message),'_blank')}}><input placeholder="Nombre" required/><input placeholder="Teléfono" required/><select><option>Modelo de interés</option>{models.map(m=><option key={m.slug}>{m.name}</option>)}</select><textarea placeholder="Mensaje o disponibilidad"/><button className="btn primary" type="submit">Enviar por WhatsApp</button></form></section> }
function Financing(){ return <main className="page"><section className="page-hero"><p className="eyebrow">Financiamiento</p><h1>Compra tu Jetour con una evaluación clara y acompañada.</h1><p>Crédito automotriz, opciones de pie, cuotas, toma de usado y orientación comercial personalizada.</p></section><section className="section cards-3">{['Evaluación comercial','Toma de usado','Cotización por modelo'].map((x,i)=><article className="feature big" key={x}><CircleDollarSign/><h3>{x}</h3><p>{['Revisamos alternativas según tu perfil y modelo de interés.','Renueva tu vehículo actual y úsalo como parte del proceso.','Recibe orientación rápida para avanzar a un 0 km.'][i]}</p></article>)}</section><Lead title="Solicita orientación de financiamiento" message="Hola Cristián, quiero evaluar financiamiento para un Jetour."/></main> }
function TestDrive(){ return <main className="page"><section className="page-hero"><p className="eyebrow">Test Drive</p><h1>Agenda una experiencia Jetour en Providencia.</h1><p>Elige el modelo de tu interés y coordinemos una visita a sucursal.</p></section><Lead title="Agendar Test Drive" message="Hola Cristián, quiero agendar un test drive Jetour."/></main> }
function Contact(){ return <main className="page"><section className="page-hero"><p className="eyebrow">Contacto</p><h1>Cristián Jiménez</h1><p>Ejecutivo de Ventas Jetour · Guillermo Morales · Sucursal Bilbao, Providencia.</p><a className="btn primary" href={wsp('Hola Cristián, quiero hablar sobre un Jetour.')} target="_blank">Escribir por WhatsApp</a></section><section className="split"><div><h2>Jetour Center Providencia</h2><p>Atención comercial directa para cotización, financiamiento, toma de usado y test drive.</p><p className="contact-line"><Phone size={18}/> +56 9 4505 5463</p><p className="contact-line"><MapPin size={18}/> Bilbao, Providencia</p></div><div className="map">Mapa referencial · Bilbao, Providencia</div></section></main> }
function Footer(){ return <footer><div><strong>Jetour Center Providencia</strong><p>Powered by Guillermo Morales · Atención comercial por Cristián Jiménez.</p></div><a href={wsp()} target="_blank">WhatsApp +56 9 4505 5463</a></footer> }
function WhatsAppButton(){ return <a className="floating-wsp" href={wsp()} target="_blank">WhatsApp</a> }
export default function App(){ return <><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/modelos" element={<Models/>}/><Route path="/modelos/:slug" element={<ModelPage/>}/><Route path="/financiamiento" element={<Financing/>}/><Route path="/test-drive" element={<TestDrive/>}/><Route path="/contacto" element={<Contact/>}/></Routes><WhatsAppButton/><Footer/></> }
