import {useState} from 'react'
import {Link,Route,Routes,useParams} from 'react-router-dom'
import {motion} from 'framer-motion'
import {IMG,benefits,modelData} from './jetourData.js'
import LeadForm from './LeadForm.jsx'

const phone='56945055463'
const clp=n=>'$'+Math.round(n||0).toLocaleString('es-CL')
const wa=t=>'https://wa.me/'+phone+'?text='+encodeURIComponent(t||'Hola, quiero cotizar un Jetour.')
function pay(price,pie,months,smart=false,vf=0){const r=.0245;const amount=price*(1-pie/100);const factor=r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1);return smart?Math.max((amount-(price*vf/100)/Math.pow(1+r,months))*factor*1.1,0):amount*factor*1.08}

function Header(){return <header className="nav"><Link className="brand" to="/"><strong>JETOUR</strong><span>Drive Your Future</span></Link><nav><Link to="/">Inicio</Link><a href="/#modelos">Modelos</a><Link to="/credito">Crédito</Link><Link to="/cotizacion">Cotización</Link><a href="/#contacto">Contacto</a></nav><div className="nav-actions"><a className="nav-cta gold" href={wa()} target="_blank" rel="noreferrer">Cotiza tu Jetour</a><a className="wsp-mini" href={wa()} target="_blank" rel="noreferrer">☎</a></div></header>}
function Card({m,i}){return <motion.article className="model-card" initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}}><Link to={'/modelos/'+m.slug}><div className="model-photo"><img src={m.img} alt={m.name}/></div><div className="model-copy"><h3>{m.name}</h3><span>{m.type}</span><strong className="cash-price">Desde {clp(m.price)}</strong><small>Precio contado referencial.</small><span className="model-link">Ver más →</span></div></Link></motion.article>}
function Simulator({base=modelData[0]}){const[slug,setSlug]=useState(base.slug),[vi,setVi]=useState(0),[pie,setPie]=useState(25),[mes,setMes]=useState(36),[vf,setVf]=useState(40);const m=modelData.find(x=>x.slug===slug)||base;const v=m.versions[Math.min(vi,m.versions.length-1)];const vals=mes===24?[50]:[30,40];const real=vals.includes(+vf)?+vf:vals[0];const smart=pay(v.price,pie,mes,true,real);const lead={modelo:m.name,version:v.name,precioContado:clp(v.price),piePorcentaje:pie+'%',pieEstimado:clp(v.price*pie/100),plazoCompraInteligente:mes,valorFuturo:real+'%',cuotaCompraInteligente:clp(smart)};return <section className="credit-section"><div className="simulator-card"><div className="sim-head"><p className="section-kicker left">Cotización crédito</p><h2>Simula tu Jetour</h2><p>Elige modelo, versión y pie disponible. Las cuotas son referenciales y deben validarse con el asesor.</p></div><div className="sim-controls"><label>Modelo<select value={slug} onChange={e=>{setSlug(e.target.value);setVi(0)}}>{modelData.map(x=><option key={x.slug} value={x.slug}>{x.name}</option>)}</select></label><label>Versión<select value={vi} onChange={e=>setVi(+e.target.value)}>{m.versions.map((x,i)=><option key={x.code} value={i}>{x.name}</option>)}</select></label><label>Pie: {pie}%<input type="range" min="20" max="50" step="5" value={pie} onChange={e=>setPie(+e.target.value)}/></label></div><div className="sim-summary"><span>Precio contado</span><strong>{clp(v.price)}</strong><span>Pie estimado</span><strong>{clp(v.price*pie/100)}</strong></div><div className="sim-results"><article><h3>Crédito convencional</h3>{[24,36,48].map(x=><div className="quote-row" key={x}><span>{x} meses</span><strong>{clp(pay(v.price,pie,x))}</strong></div>)}</article><article><h3>Compra inteligente</h3><div className="inline-selects"><select value={mes} onChange={e=>setMes(+e.target.value)}><option value="24">24 meses</option><option value="36">36 meses</option><option value="48">48 meses</option></select><select value={real} onChange={e=>setVf(+e.target.value)}>{vals.map(x=><option key={x} value={x}>VF {x}%</option>)}</select></div><div className="quote-main"><span>Cuota referencial</span><strong>{clp(smart)}</strong></div><small>24 meses: VF 50%. 36 y 48 meses: VF 30% o 40%.</small></article></div><LeadForm lead={lead}/></div></section>}
function Home(){return <main><section className="hero" id="inicio"><div className="hero-bg"><img src={IMG.hero} alt="Jetour T2"/></div><div className="hero-desert"/><div className="hero-city"/><div className="hero-overlay"/><motion.div className="hero-content" initial={{opacity:0,y:26}} animate={{opacity:1,y:0}}><h1>Vive sin límites</h1><h2>Explora lo extraordinario</h2><p className="lead">Diseño, tecnología y desempeño se unen para acompañarte en cada camino que elijas.</p><div className="hero-actions"><a className="btn gold" href="#modelos">Conoce nuestros modelos</a><Link className="btn light" to="/credito">Simular crédito</Link></div></motion.div></section><section className="benefit-strip">{benefits.map(b=><article key={b.title}><div>{b.icon}</div><strong>{b.title}</strong><p>{b.text}</p></article>)}</section><section className="section dark" id="modelos"><p className="section-kicker">Nuestros modelos</p><div className="model-grid">{modelData.map((m,i)=><Card key={m.slug} m={m} i={i}/>)}</div></section><section className="advisor-band" id="contacto"><div><p>Asesor comercial</p><h2>Cristián Jiménez</h2><span>Estoy para ayudarte siempre.</span></div><div><strong>Estoy para ayudarte siempre</strong><p>Cotiza, consulta y agenda tu test drive conmigo directamente.</p></div><a className="btn gold" href={wa('Hola Cristián, quiero cotizar un Jetour.')} target="_blank" rel="noreferrer">Escríbeme por WhatsApp</a></section></main>}
function ModelPage(){const {slug}=useParams();const m=modelData.find(x=>x.slug===slug)||modelData[0];return <main className="model-page"><section className="model-hero"><div><p className="eyebrow dark">Jetour {m.tag}</p><h1>{m.name}</h1><p>{m.desc}</p><strong>Precio contado desde {clp(m.price)}</strong><div className="hero-actions"><a className="btn dark" href={wa('Hola Cristián, quiero cotizar el Jetour '+m.name)} target="_blank" rel="noreferrer">Cotizar este modelo</a><Link className="btn outline" to="/credito">Simular crédito</Link></div></div><img src={m.img} alt={m.name}/></section><section className="model-content"><div className="gallery"><h2>Imágenes del modelo</h2><p>Galería referencial con material oficial. Luego reemplazaremos estas imágenes por fotos reales de la sucursal.</p><div>{m.gallery.map((g,i)=><figure key={i}><img src={g.img} alt={g.title}/><figcaption>{g.title}</figcaption></figure>)}</div></div><div className="tech-sheet"><p className="section-kicker left">Ficha técnica</p><h2>{m.name}</h2><dl>{Object.entries(m.specs).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><h3>Equipamiento destacado</h3><ul>{m.features.map(x=><li key={x}>{x}</li>)}</ul></div></section><section className="versions"><h2>Versiones y precio contado</h2><div className="version-table">{m.versions.map(v=><article key={v.code}><strong>{v.name}</strong><span>{v.code}</span><span>{v.motor} · {v.hp} HP</span><b>{clp(v.price)}</b></article>)}</div><p>Pide a tu asesor precios especiales de financiamiento.</p></section><Simulator base={m}/></main>}
function CreditPage(){return <main className="model-page"><section className="model-hero credit-hero"><div><p className="eyebrow dark">Cotización crédito</p><h1>Simula tu Jetour</h1><p>Completa tu simulación y envía tus datos para validación comercial.</p></div><img src={IMG.t2} alt="Jetour crédito"/></section><Simulator/></main>}
export default function Root(){return <><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/credito" element={<CreditPage/>}/><Route path="/cotizacion" element={<CreditPage/>}/><Route path="/modelos/:slug" element={<ModelPage/>}/></Routes><footer><div><strong>JETOUR</strong><span>Drive Your Future</span></div><div><strong>ASESOR COMERCIAL</strong><span>Cristián Jiménez</span></div><a href={wa()} target="_blank" rel="noreferrer">WhatsApp</a></footer><a className="floating" href={wa()} target="_blank" rel="noreferrer">WhatsApp</a></>}
